services:
  db:
    image: mysql:8.0
    container_name: turma-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: escola_db
    ports:
      - "3306:3306"
    volumes:
      - meus-dados-mysql:/var/lib/mysql

volumes:
  meus-dados-mysql:
